version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "PyGithub"
      - dependency-name: "requests"
      - dependency-name: "urllib3"
