# GitHub Teams that are authorised to communicate with FNALbuild.
# GitHub usernames are not supported.

# All teams must be created inside the Mu2e organisation at
# https://github.com/orgs/Mu2e/teams

# Any requests to edit this file should be closely checked.

all:
  - write

main:
  - fnalbuild-users

Mu2eII_SM21:
  - mu2eii_sm21_ci
